autonomy_dependencies:
- name: open-autonomy
  version: 0.19.5
  location: remote
  url: https://api.github.com/repos/valory-xyz/open-autonomy
  plugins: &id001
  - open-aea-test-autonomy
  extras: null
- name: open-aea
  version: 1.65.0
  location: remote
  url: https://api.github.com/repos/valory-xyz/open-aea
  plugins: &id002
  - open-aea-ledger-ethereum
  - open-aea-ledger-solana
  - open-aea-ledger-cosmos
  - open-aea-cli-ipfs
  extras: null
- name: stations_stations
  version: 0.1.19
  location: remote
  url: https://api.github.com/repos/StationsStation/stations_station
  plugins: null
  extras: null
poetry_dependencies:
- name: open-autonomy
  version: 0.19.5
  location: remote
  url: https://api.github.com/repos/valory-xyz/open-autonomy
  plugins: *id001
  extras: null
- name: open-aea
  version: 1.65.0
  location: remote
  url: https://api.github.com/repos/valory-xyz/open-aea
  plugins: *id002
  extras: null
- name: autonomy-dev
  version: 0.2.148
  location: remote
  url: https://api.github.com/repos/8ball030/auto_dev
  plugins: null
  extras:
  - all
