agent_name: bal_squared
author: eightballer
version: 0.1.0
license: Apache-2.0
description: Simple Agent to demonstrate Dex-Cex Arbitrage
aea_version: '>=1.55.0, <3.0.0'
fingerprint:
  logger_setup.py: bafybeicboqnvizlhdsnmlncvayrswskbyw6vshi34bnrs75qshbz3wdlqu
  no-queue-logging.yaml: bafybeib6k2usocdkxtz6nqa2igxbwkp7f72inrsxtufyy3pttpbojxysay
  tests/test_derive_trader_agent.py: bafybeif4ycyf6kcisfxm6gr224lqxhei4dwk7apfoux4vvpmtoots3ddri
fingerprint_ignore_patterns: []
connections:
- eightballer/apprise_wrapper:0.1.0:bafybeib46mwxydjapluicictavkcsmt2jpppkkru4lqhv3fwx5pbmngi2u
- eightballer/ccxt_wrapper:0.1.0:bafybeidth26t3wye3pk6gud23ngpg47z5yybp44nuxznf5zc4i2addvcgi
- eightballer/dcxt:0.1.0:bafybeidghpug5akrvl4rcnce3euc34fefn7xxcjxcndhzsm4euzsz2gu7m
- eightballer/http_client:0.1.0:bafybeic3cvg5pyze5w2mdcnukosep7egyglnidcycliyatdnddtvufgvta
- eightballer/http_server:0.1.0:bafybeieoixhtwm6f6ednwjli3sutbgklsqhnjkgxyxeflepa4qagx5gfr4
- eightballer/p2p_libp2p_client:0.1.0:bafybeicdxaxzy6257w4c7zxhavxocuvbd74zrkjwkpu74mfqxgtf6pmfhi
- eightballer/prometheus:0.1.1:bafybeig7p3tzs7x4awcxjr7ctxljr6h7mrc2c36thnab6zoteualgivj6e
- valory/abci:0.1.0:bafybeib5ggind6xiilp4uclqhh27zj6ga4dfy7mdd5nxtzyr55mf3uztlu
- valory/http_client:0.23.0:bafybeiglmlwp73njl6ijmruak5ivpfx7hv6gamap72ygsvd7jmonrdtbkm
- valory/ipfs:0.1.0:bafybeifepnczgwd4pa5y535kfjphj44mbbkm7ljb6iatmxmlcu3e5mauv4
- valory/ledger:0.19.0:bafybeicib5velkx7ttqqxrbeguklyu5xeifanzqdecwalqpu3olmrjm5dq
contracts:
- eightballer/erc_20:0.1.0:bafybeiewlvc62xn6flmzn2dodqw3w6p3w5jqwkx36w5caznf6zjph7t2se
- valory/service_registry:0.1.0:bafybeidm5ki2bnk52janpeabjc6lsmn6w2l5zocfpnbigyfozuriv4atvy
- zarathustra/derolas_staking:0.1.0:bafybeicyuprz3bnyblmkmbbwenvh76hnqgxf7c2jkmvxe3to5ye3lnttsi
protocols:
- eightballer/approvals:0.1.0:bafybeid72h5vqtg4aqwluzdfwr5plj5mnkrd7yi6dpzzs3qptzugngxgyu
- eightballer/balances:0.1.0:bafybeieunsu3sfhqsh5selbbrhijedgrngjfsrzqhoevxwpv6shmlh6gni
- eightballer/default:0.1.0:bafybeidxdrzt2lqcig5cfdaju4kx2jjlbmmrvep34blhhgvm6cyr6qtlge
- eightballer/http:0.1.0:bafybeigvajfairsqyira3idfhacj7l4vq25mjgyti76et5ryhspbk5uvbi
- eightballer/markets:0.1.0:bafybeih2anyaxbqibhlufqvqx5trixarl4kmfhtatnortdrck3grjjgaga
- eightballer/ohlcv:0.1.0:bafybeicmclhj5db6fs2kf22hdgijw5hdigrii2ub4vcxcxuh7n4zxryp34
- eightballer/order_book:0.1.0:bafybeibdkpj3qy7gcybni7goneqe75cgeqcialsv6he3ozmzgqqms7oxfu
- eightballer/orders:0.1.0:bafybeifsi7b6pw5eifxelco7ibxjcegmhxqcyl2t2ckclmwyjdyn7wef5e
- eightballer/positions:0.1.0:bafybeicqzks7yh2zkwder2wrmt525wovl3yey2q3gcrjmi3xtthanaqhqa
- eightballer/prometheus:1.0.0:bafybeiedkmjjqbxyid67hwhpkvyknst5rdtn5pazs6rtaa3mj6r2buwl7q
- eightballer/spot_asset:0.1.0:bafybeifjra7gn24377acdpxa2p4h4u4kbfmkxw26qh5s3k2vpkb7h54d6e
- eightballer/tickers:0.1.0:bafybeigx2wpxkygmcc5c4stn44wbmjgxfojkutghaptcr2cjh5z4ojlwf4
- eightballer/user_interaction:0.1.0:bafybeibotsfodi6jkoemmt4tpwecxkj7p3dphinuzuakh5z2cisckxxp6m
- open_aea/signing:1.0.0:bafybeign4u6o3jtz2kuelpuhrmzosbyix2iwf7ifxythigrcuef4ybmuna
- valory/abci:0.1.0:bafybeifoxrhaouglnxqedcwybz7gt7tsnqwviqy2sl4fuzwxgwxppe46my
- valory/acn:1.1.0:bafybeihjy675e5epm3jpdmo5owtkq4xyoxaif2rnyanrbvly63we37fdbm
- valory/contract_api:1.0.0:bafybeidpch6cvuweq5x4h6ummnnw5xynmfsbj3sxm2m63seuqizrmvpd3e
- valory/http:1.0.0:bafybeic2kgzaesbi6tio5wohr6sj6lq7zaxa3mxhwza52qmdlm6ai3lmrm
- valory/ipfs:0.1.0:bafybeid56ir7oghnxugb2wyszjcj6l5siznimjdm5av3f24kp44ci7kg2q
- valory/ledger_api:1.0.0:bafybeic5qfhodpwqjdkwxs4gzummpc3dxbpn4egg7s7f2gibfopa4nxz4i
- valory/tendermint:0.1.0:bafybeicpmyfpmoobve6eqjbrs4ht5apl5xvnikmsg4wdcpwljy42zhghl4
- zarathustra/asset_bridging:0.1.0:bafybeiaisse2jqpfvb2jqhgnwsa3p2b6v7ommontm5llagtfphqgkmyzkq
skills:
- eightballer/abstract_round_abci:0.1.0:bafybeifazgkeuphhaiml5v26weiio6qpaa2ax57hnnbwijs5gpxs6gxhna
- eightballer/prometheus:0.1.0:bafybeifnee635625vabb45qotvzopgkets5dlwk3mwae3lrhr4bqfpuxyy
- eightballer/simple_fsm:0.1.0:bafybeidxoirmjovesfhruo52gxwo6jdoswzsb4lp5o3w6fjvcvyvqw2h2m
- eightballer/trading_state:0.1.0:bafybeidlotrvpgyvesqs4pscztom23szlh5ke5bgoqeqnztjwtt2z2vc4i
- valory/abstract_abci:0.1.0:bafybeieactg2rjpeomiqzuu3nbanoxtfdfk5vwil2dqg5ceh6z7kxl7snq
- zarathustra/derolas_automator_abci_app:0.1.0:bafybeibvwl2utbfarxlbi6d7a6rb75tpirbg74udk5t5vbrwlvqygt4e4a
customs:
- eightballer/lbtc_arbitrage:0.1.0:bafybeifwhndod6v7za5qsfek3us7i2kim4h5zl7tbhaz2mq764727rkkka
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: true
  handlers:
    queue:
      class: logger_setup.QueuedHandler
      queue_size: 10000
      handler_names:
      - console
      - logfile
      handler_configs:
        console:
          class: logger_setup.BufferedHandler
          formatter: standard
          level: INFO
        logfile:
          class: logging.handlers.TimedRotatingFileHandler
          filename: log.jsonl
          formatter: json
          level: INFO
          when: D
          interval: 1
          backupCount: 7
      formatter_configs:
        standard:
          class: logger_setup.ShortNameFormatter
          format: '[%(levelname)s]%(message)s'
        detailed:
          format: '[%(levelname)s|%(pathname)s|L%(lineno)d] %(asctime)s: %(message)s'
          datefmt: '%Y-%m-%dT%H:%M:%S%z'
        json:
          class: logger_setup.JSONFormatter
          datefmt: '%Y-%m-%dT%H:%M:%S%z'
  loggers:
    aea:
      handlers:
      - queue
      level: INFO
      propagate: false
  version: 1
dependencies:
  open-aea-ledger-ethereum: {}
  rich: {}
default_connection: null
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: ${HTTP_PORT:int:8889}
  target_skill_id: eightballer/trading_state:0.1.0
---
public_id: eightballer/prometheus:0.1.1:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: ${PROM_PORT:int:8717}
---
public_id: valory/abci:0.1.0:bafybeihofnsokowicviac6yz3uhur52l3mf54s2hz4i2je5ie4vlruouga
type: connection
config:
  host: ${str:localhost}
  port: ${ABCI_PORT:int:26659}
  use_tendermint: ${bool:false}
  target_skill_id: eightballer/chained_dex_app:0.1.0
---
public_id: eightballer/ccxt_wrapper:0.1.0:bafybeidyrx74rtv7x3h757y44cc5xle6crnnklwpe6jrgwmsfjdtk5xabe
type: connection
config: {}
---
public_id: eightballer/apprise_wrapper:0.1.0
type: connection
config:
  endpoints:
  - ${APPRISE_ENDPOINT:str:null}
---
public_id: eightballer/dcxt:0.1.0:bafybeid2knx2lkd5jz64a357vtcz35gfjtoqey4shmmjtygl3r7dx6kvwq
type: connection
config:
  exchanges:
  - name: balancer
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: ethereum
    rpc_url: ${ETHEREUM_RPC:str:https://eth.llamarpc.com}
    etherscan_api_key: NULL_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: base
    rpc_url: ${BASE_RPC:str:https://base.drpc.org}
    etherscan_api_key: NULL_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: arbitrum
    rpc_url: ${ARBITRUM_RPC:str:https://arbitrum.drpc.org}
    etherscan_api_key: NULL_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: gnosis
    rpc_url: ${GNOSIS_RPC:str:https://gnosis.drpc.org}
    etherscan_api_key: NULL_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: polygon
    rpc_url: ${POLYGON_RPC:str:https://polygon.drpc.org}
    etherscan_api_key: NULL_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: optimism
    rpc_url: ${OPTIMISM_RPC:str:https://optimism.drpc.org}
    etherscan_api_key: NULL_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: mode
    rpc_url: ${MODE_RPC:str:https://mainnet.mode.network}
    etherscan_api_key: NULL_KEY
---
public_id: eightballer/simple_fsm:0.1.0
type: skill
models:
  arbitrage_strategy:
    args:
      dexs:
        balancer: ${BAL_CHAINS:list:["arbitrum","base"]}
      strategy_public_id: eightballer/lbtc_arbitrage:0.1.0
      strategy_init_kwargs:
        base_asset: ${BASE_ASSET:str:OLAS}
        quote_asset: ${QUOTE_ASSET:str:USDC}
        order_size: ${ORDER_SIZE:float:250}
        min_profit: ${MIN_PROFIT:float:0.00}
        max_open_orders: ${MAX_OPEN_ORDERS:int:1000}
      cooldown_period: ${COOLDOWN_PERIOD:int:60}
      cexs: ${list:[]}
      bridging_enabled: false
