agent_name: derive_arbitrage_agent
author: eightballer
version: 0.1.0
license: Apache-2.0
description: Simple Agent to demonstrate Dex-Cex Arbitrage
aea_version: '>=1.55.0, <3.0.0'
fingerprint:
  __init__.py: bafybeigfigcohr63kijc3kwb2oli7nntgqt4ooiztsl7eett3d6ycldaru
  logger_setup.py: bafybeicboqnvizlhdsnmlncvayrswskbyw6vshi34bnrs75qshbz3wdlqu
  no-queue-logging.yaml: bafybeib6k2usocdkxtz6nqa2igxbwkp7f72inrsxtufyy3pttpbojxysay
  tests/test_derive_trader_agent.py: bafybeif4ycyf6kcisfxm6gr224lqxhei4dwk7apfoux4vvpmtoots3ddri
fingerprint_ignore_patterns: []
connections:
- eightballer/apprise_wrapper:0.1.0:bafybeiafvyh2l3imqusjn374wnnet6gzhyvc4o5wrczdlt3mz535og7elm
- eightballer/ccxt_wrapper:0.1.0:bafybeidth26t3wye3pk6gud23ngpg47z5yybp44nuxznf5zc4i2addvcgi
- eightballer/dcxt:0.1.0:bafybeia6nmlaz5cgyelc7avislgla4brv5vksixgu5smbjvkol7z7kpkfm
- eightballer/http_client:0.1.0:bafybeigqr2eudiwksmr2cavk6as63li2oqf3x2edwzvs5vepntuqhemnge
- eightballer/http_server:0.1.0:bafybeieispawqnpoeqidgkt7u7vsynualtcmbs3vsgggpb6hzkdsyd3fve
- eightballer/p2p_libp2p_client:0.1.0:bafybeifhzqibd6dlddkntsv6iyjkltfm25snfify3v5r6dobd47qnomisa
- eightballer/prometheus:0.1.1:bafybeicgvmn5eo57jotbcwasjqlmzog3ss5dvvembw7jaytfz33z4kbaoa
- valory/abci:0.1.0:bafybeibtiw6wlcrkov6vshboixsjgaeodkhxjppk2fbzwleknbp24ci42i
- valory/http_client:0.23.0:bafybeifcxgtlp3rcuptxtu7fkipauuxl3mcbawuofe6nnejhnq3mjw2rjq
- valory/ipfs:0.1.0:bafybeif7exoq2viwhfgfcjplxq73hnxvgpsx7pwshhntx6aekza25mdwli
- valory/ledger:0.19.0:bafybeiflmep26twrfk25olhyxuagceaa2cfvg5qtgsisaxh6z4pdapg6dy
contracts:
- eightballer/erc_20:0.1.0:bafybeiewlvc62xn6flmzn2dodqw3w6p3w5jqwkx36w5caznf6zjph7t2se
- eightballer/spl_token:0.1.0:bafybeieozewfydqtdlygehzkhofque6klpcr6pkkcx5bd3eug7uuwcl7nm
- valory/service_registry:0.1.0:bafybeigcr4y6ylathz5owdyq6nhvrdpv5unyeb3ol3h3xbncq24useqlpa
- vybe/jupitar_swap:0.1.0:bafybeiee75r3x6e5dvnkzmzio6p5xecnoq3lzu3ab2fwrckvbp4a6vr65e
protocols:
- eightballer/balances:0.1.0:bafybeieunsu3sfhqsh5selbbrhijedgrngjfsrzqhoevxwpv6shmlh6gni
- eightballer/default:0.1.0:bafybeidxdrzt2lqcig5cfdaju4kx2jjlbmmrvep34blhhgvm6cyr6qtlge
- eightballer/http:0.1.0:bafybeigvajfairsqyira3idfhacj7l4vq25mjgyti76et5ryhspbk5uvbi
- eightballer/markets:0.1.0:bafybeih2anyaxbqibhlufqvqx5trixarl4kmfhtatnortdrck3grjjgaga
- eightballer/ohlcv:0.1.0:bafybeicmclhj5db6fs2kf22hdgijw5hdigrii2ub4vcxcxuh7n4zxryp34
- eightballer/order_book:0.1.0:bafybeibdkpj3qy7gcybni7goneqe75cgeqcialsv6he3ozmzgqqms7oxfu
- eightballer/orders:0.1.0:bafybeifsi7b6pw5eifxelco7ibxjcegmhxqcyl2t2ckclmwyjdyn7wef5e
- eightballer/positions:0.1.0:bafybeicqzks7yh2zkwder2wrmt525wovl3yey2q3gcrjmi3xtthanaqhqa
- eightballer/prometheus:1.0.0:bafybeiedkmjjqbxyid67hwhpkvyknst5rdtn5pazs6rtaa3mj6r2buwl7q
- eightballer/spot_asset:0.1.0:bafybeifjra7gn24377acdpxa2p4h4u4kbfmkxw26qh5s3k2vpkb7h54d6e
- zarathustra/asset_bridging:0.1.0:bafybeiaisse2jqpfvb2jqhgnwsa3p2b6v7ommontm5llagtfphqgkmyzkq
- eightballer/tickers:0.1.0:bafybeigx2wpxkygmcc5c4stn44wbmjgxfojkutghaptcr2cjh5z4ojlwf4
- eightballer/approvals:0.1.0:bafybeid72h5vqtg4aqwluzdfwr5plj5mnkrd7yi6dpzzs3qptzugngxgyu
- eightballer/user_interaction:0.1.0:bafybeidhs7hwsfinvgkkyodgq5qoolg5i4rf5vr2c2xcuvkbyoodefcvoq
- open_aea/signing:1.0.0:bafybeigalbjxbpl6pezijj6it2zspjcjy3znm66t5ygbe4kz5kxcnbu65y
- valory/abci:0.1.0:bafybeigdi6wsbdn2nv7clzhnuhki3taywgiiajwawdaat57o5ntlgqj2qe
- valory/acn:1.1.0:bafybeihrfsualuoxnwxfmhgbbyty4ttqijuwzcesg3kwsqxfzcmxc7t4rm
- valory/contract_api:1.0.0:bafybeigzv2yxgkednegkiepkm5uxv2ekdn3y5czvh6ycba6t7n3k2otu24
- valory/http:1.0.0:bafybeiczj4q3lkuiwhb6vzn7ptxifqgjtnvl7722t7c4eystbuel5cd34i
- valory/ipfs:0.1.0:bafybeib7jhgyocjwdq3r5wzq3z4qeubj3dwi3aqjn2uxzuwnjp5fhvafcu
- valory/ledger_api:1.0.0:bafybeicwup3faznzvuciqkljejo2c6gbv3dliaglscf5bibu6633tylkfq
- valory/tendermint:0.1.0:bafybeif5wq5i2ugr66alniej2bk4vws5sikal7otx674y5kz52e3ulo2qm
skills:
- eightballer/abstract_round_abci:0.1.0:bafybeibaxi47gozccfsf7j2bizthfw7t6zs5ajfynq5eju42bnvb5glc7i
- eightballer/prometheus:0.1.0:bafybeidfz7ms5n7f27fywsm4gbxy6ykztdctln44cvuemmyuww2igonwby
- eightballer/simple_fsm:0.1.0:bafybeidnf5nvdigqy2wdsvl6oibjqeyctoisasjn6odonns42pslmjjrnu
- eightballer/trading_state:0.1.0:bafybeihvzriswvf2oijlnkp25at65uiol763h6t26v3etbgsa2erhbaana
- valory/abstract_abci:0.1.0:bafybeidr3dqykchbw7rnmxcrp3qkuafk24pyvr7zehfbkcfon62qwuft7y
- zarathustra/derolas_automator_abci_app:0.1.0:bafybeie66kgmojdwlcgx7g2vovdju3pu6boix3z5ypy6lttrg6fma6fq3u
customs:
- eightballer/lbtc_arbitrage:0.1.0:bafybeifwhndod6v7za5qsfek3us7i2kim4h5zl7tbhaz2mq764727rkkka
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: true
  handlers:
    queue:
      class: logger_setup.QueuedHandler
      queue_size: 10000
      handler_names:
      - console
      - logfile
      handler_configs:
        console:
          class: logger_setup.BufferedHandler
          formatter: standard
          level: INFO
        logfile:
          class: logging.handlers.TimedRotatingFileHandler
          filename: log.jsonl
          formatter: json
          level: INFO
          when: D
          interval: 1
          backupCount: 7
      formatter_configs:
        standard:
          class: logger_setup.ShortNameFormatter
          format: '[%(levelname)s]%(message)s'
        detailed:
          format: '[%(levelname)s|%(pathname)s|L%(lineno)d] %(asctime)s: %(message)s'
          datefmt: '%Y-%m-%dT%H:%M:%S%z'
        json:
          class: logger_setup.JSONFormatter
          datefmt: '%Y-%m-%dT%H:%M:%S%z'
  loggers:
    aea:
      handlers:
      - queue
      level: INFO
      propagate: false
  version: 1
dependencies:
  open-aea-ledger-ethereum: {}
  rich: {}
default_connection: null
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: ${HTTP_PORT:int:8889}
  target_skill_id: eightballer/trading_state:0.1.0
---
public_id: eightballer/prometheus:0.1.1:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: ${PROM_PORT:int:8717}
---
public_id: valory/abci:0.1.0:bafybeihofnsokowicviac6yz3uhur52l3mf54s2hz4i2je5ie4vlruouga
type: connection
config:
  host: ${str:localhost}
  port: ${ABCI_PORT:int:26659}
  use_tendermint: ${bool:false}
  target_skill_id: eightballer/chained_dex_app:0.1.0
---
public_id: eightballer/ccxt_wrapper:0.1.0:bafybeidyrx74rtv7x3h757y44cc5xle6crnnklwpe6jrgwmsfjdtk5xabe
type: connection
config: {}
---
public_id: eightballer/apprise_wrapper:0.1.0
type: connection
config:
  endpoints:
  - ${APPRISE_ENDPOINT:str:null}
---
public_id: eightballer/dcxt:0.1.0:bafybeid2knx2lkd5jz64a357vtcz35gfjtoqey4shmmjtygl3r7dx6kvwq
type: connection
config:
  exchanges:
  - name: cowswap
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: ethereum
    rpc_url: ${ETHEREUM_RPC:str:https://eth.llamarpc.com}
  - name: cowswap
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: base
    rpc_url: ${BASE_RPC:str:https://base.llamarpc.com}
  - name: cowswap
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: arbitrum
    rpc_url: ${ARBITRUM_RPC:str:https://arbitrum.drpc.org}
  - name: cowswap
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: gnosis
    rpc_url: ${GNOSIS_RPC:str:https://gnosis.drpc.org}
  - name: derive
    key_path: ethereum_private_key.txt
    wallet: ${DERIVE_WALLET:str:0x1234}
    subaccount_id: ${DERIVE_SUBACCOUNT_ID:int:1234}
    ledger_id: derive
    environment: prod
---
public_id: eightballer/simple_fsm:0.1.0
type: skill
models:
  arbitrage_strategy:
    args:
      dexs:
        derive:
        - derive
        cowswap: ${COW_CHAINS:list:["arbitrum"]}
        balancer: []
      strategy_public_id: eightballer/lbtc_arbitrage:0.1.0
      strategy_init_kwargs:
        base_asset: ${BASE_ASSET:str:OLAS}
        quote_asset: ${QUOTE_ASSET:str:USDC}
        order_size: ${ORDER_SIZE:float:100}
        min_profit: ${MIN_PROFIT:float:0.01}
        max_open_orders: ${MAX_OPEN_ORDERS:int:100}
      cooldown_period: ${COOLDOWN_PERIOD:int:30}
      cexs: ${list:[]}
      bridging_enabled: true
