apiVersion: v1
entries:
  derolas-agents:
  - apiVersion: v2
    appVersion: 0.1.41
    created: "2026-01-19T12:17:09.437131587Z"
    description: A Helm chart for Kubernetes
    digest: aa3b96b197628935b595260065b0b3e4d2d7bcfa99c3a90d97a3f6640bb81017
    name: derolas-agents
    type: application
    urls:
    - https://stationsstation.github.io/capitalisation_station/charts/derolas-agents-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-19T12:17:09.436595748Z"
