agent_name: chained_dex_app
author: eightballer
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.35.0, <2.0.0'
fingerprint:
  tests/__init__.py: bafybeiepblz7lugbzxz56ocqdxykmndj26fnsfcuccqh5l4gevgyl7w2yi
  tests/test_agent.py: bafybeidrb6p7zrp3omjt4tacnwevo75zmu5t324imbpz4jb3jck6gc5pai
fingerprint_ignore_patterns: []
connections:
- eightballer/ccxt:0.1.0:bafybeifzbofi44yvw3k5uowdojtgdacjakmro4ai4lyyu4bgdtibjlxzyq
- eightballer/dcxt:0.1.0:bafybeibrbc4ribjw2sbmf6e2iyyjhytq3n7ldaci2asqfrnyul7fztgcyi
- eightballer/http_client:0.1.0:bafybeidxqvcgobltkb5rgokakcfo25ntfhlffmpzqap6oid4ttmwbvn4qi
- eightballer/http_server:0.1.0:bafybeid7u7cx2smnb3iz6zs6gt3k4ijwevm6yqqfo4pmziqoubl2p52ele
- eightballer/prometheus:0.1.1:bafybeibiy3nvia5xjvey5gmwv56vi4w7kjbbb5xcug2lwp4f7ylnfpw2wu
- valory/abci:0.1.0:bafybeiejymu4ul62zx6weoibnlsrfprfpjnplhjefz6sr6izgdr4sajlnu
- valory/http_client:0.23.0:bafybeihi772xgzpqeipp3fhmvpct4y6e6tpjp4sogwqrnf3wqspgeilg4u
- valory/ipfs:0.1.0:bafybeiegnapkvkamis47v5ioza2haerrjdzzb23rptpmcydyneas7jc2wm
- valory/ledger:0.19.0:bafybeigntoericenpzvwejqfuc3kqzo2pscs76qoygg5dbj6f4zxusru5e
- valory/p2p_libp2p_client:0.1.0:bafybeid3xg5k2ol5adflqloy75ibgljmol6xsvzvezebsg7oudxeeolz7e
contracts:
- valory/service_registry:0.1.0:bafybeihafe524ilngwzavkhwz4er56p7nyar26lfm7lrksfiqvvzo3kdcq
- eightballer/erc_20:0.1.0:bafybeibmueua3l5cxfofbbnce3r6pt46yec26arp3vecn34mycqtyjsvzq
protocols:
- eightballer/balances:0.1.0:bafybeicjxjwmr4wubghu4fa3cdg7dhwpy6b3dhvuaqbzem3jvycooyyazm
- eightballer/default:0.1.0:bafybeiful5q7lvyogogzbc6ax3gt6wptk65chfu2cy7azndr4xxsejctq4
- eightballer/http:0.1.0:bafybeieoom2ajzvurwsjbivx23dwilarfzkihgqpgqp43ypowpr5xdyjr4
- eightballer/markets:0.1.0:bafybeicr27ryhnm7l4uanyke6mnxchpva3aqe5cwrnxklcciojba3uxc3q
- eightballer/ohlcv:0.1.0:bafybeichagw6zkosbtkmv2vhpjzlxo3cbgz42eqzukoonirtlfi3hsc57q
- eightballer/order_book:0.1.0:bafybeiezpo43d27dfeucpjgy3aouspbddoj36oebgsnun3hs3ocepuoceu
- eightballer/orders:0.1.0:bafybeics2wkusxfbu4atidjvczlrjjfp3oldpg4mezhcae2qzdyok5djgq
- eightballer/positions:0.1.0:bafybeiembq4kn4fi6mkr6albuuvdx4wcg2pilkz74m5lsajsk7uq5e4sdm
- eightballer/prometheus:1.0.0:bafybeicjwq2wgka7g5dnn5dnuzstfzt5fbbgknvd5lwk7uzwtz3h6yg5du
- eightballer/spot_asset:0.1.0:bafybeidkdoylcvcw3evi7eyn2jdp3lt3zbvyz6ohtqsm4jmr5pnksgnstu
- eightballer/tickers:0.1.0:bafybeifb3albdq62qmhwclq7djtush4tlsmeypoq7tim2kunhdrus6yrqe
- open_aea/signing:1.0.0:bafybeihv62fim3wl2bayavfcg3u5e5cxu3b7brtu4cn5xoxd6lqwachasi
- valory/abci:0.1.0:bafybeiaqmp7kocbfdboksayeqhkbrynvlfzsx4uy4x6nohywnmaig4an7u
- valory/acn:1.1.0:bafybeidluaoeakae3exseupaea4i3yvvk5vivyt227xshjlffywwxzcxqe
- valory/contract_api:1.0.0:bafybeidgu7o5llh26xp3u3ebq3yluull5lupiyeu6iooi2xyymdrgnzq5i
- valory/http:1.0.0:bafybeifugzl63kfdmwrxwphrnrhj7bn6iruxieme3a4ntzejf6kmtuwmae
- valory/ipfs:0.1.0:bafybeiftxi2qhreewgsc5wevogi7yc5g6hbcbo4uiuaibauhv3nhfcdtvm
- valory/ledger_api:1.0.0:bafybeihdk6psr4guxmbcrc26jr2cbgzpd5aljkqvpwo64bvaz7tdti2oni
- valory/tendermint:0.1.0:bafybeig4mi3vmlv5zpbjbfuzcgida6j5f2nhrpedxicmrrfjweqc5r7cra
skills:
- eightballer/chained_dex_app:0.1.0:bafybeihxn5uahnt5zo3bqymlqlcuygmlouy5kezqnow2bjy6ygz2uskly4
- eightballer/dex_data_retrieval:0.1.0:bafybeiekcwvr22rptsur55psrhcvbacvnc3p3v5er7vhvdx6h46zcboxxy
- eightballer/metrics:0.1.0:bafybeiau3srj3k5wth4sa3sn4aijcph7tuigkccplm67tuetjqj72ypkje
- eightballer/prometheus:0.1.0:bafybeibssw6lcshlnxnwqcjebjxiwtnyw3nki7jkbnh4lnvtcq6aaqni5e
- valory/abstract_abci:0.1.0:bafybeidz54kvxhbdmpruzguuzzq7bjg4pekjb5amqobkxoy4oqknnobopu
- valory/abstract_round_abci:0.1.0:bafybeicogmx5rixmmsvelrpkxeegrldnjwh4thyngdagycnp2e2ee4amva
- valory/registration_abci:0.1.0:bafybeifkra3zbg5e4rhsuvjygracgp2jivqxezag7r4fshxetfp2jukkxe
- valory/reset_pause_abci:0.1.0:bafybeiefmld4bv22k7rjxzmnvhfygizrftgkvrtputgfuvwrenrdpx233q
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: true
  version: 1
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      level: INFO
      stream: ext://sys.stdout
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: INFO
  loggers:
    aea:
      handlers:
      - console
      - logfile
      level: INFO
      propagate: false
dependencies:
  open-aea-ledger-ethereum: {}
customs: []
default_connection: null
---
public_id: valory/ipfs:0.1.0:bafybeiatjutuiav7oxl4hszy3oypdwuetr6crjpminush54c5k4nbeciv4
type: connection
config:
  ipfs_domain: /dns/registry.autonolas.tech/tcp/443/https
---
public_id: valory/abci:0.1.0:bafybeihofnsokowicviac6yz3uhur52l3mf54s2hz4i2je5ie4vlruouga
type: connection
config:
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
  target_skill_id: eightballer/chained_dex_app:0.1.0
---
public_id: eightballer/chained_dex_app:0.1.0:bafybeicmuthcay6doky6sgy235n52chsk5fkzswpvyg5s4yeptvmzmxoqy
type: skill
models:
  params:
    args:
      dex_data_retrieval_config:
        enabled: true
        reporting_enabled: true
        exchange_ids:
        - balancer_optimism
        - balancer_ethereum
        - balancer_base
        extra_kwargs: {}
        backoff: 1.0
        retries: 3
      max_healthcheck: 1200
      on_chain_service_id: null
      reset_pause_duration: 10
      reset_tendermint_after: 10
      round_timeout_seconds: 35.0
      service_registry_address: null
      setup:
        all_participants: ${list:["0x92d9610BC04aa4F0162e45B031b7fa6d76d4B4b3"]}
        consensus_threshold: 1
        safe_contract_address: '0x0000000000000000000000000000000000000000'
      share_tm_config_on_startup: false
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_p2p_url: ${str:localhost:26656}
      tendermint_url: ${str:http://localhost:26657}
      validate_timeout: 1205
---
public_id: eightballer/prometheus:0.1.1:bafybeiemx6sryvqdjied7xqqxge5vyplyyzyiro4a4pubqpjrps4sxm7xe
type: connection
config:
  port: 8888
  host: 0.0.0.0
---
public_id: eightballer/http_server:0.1.0:bafybeih7adv4sxwek3g3ns6x6sguhnos7ixmsdaywqdaxhexczm2gotivm
type: connection
config:
  target_skill_id: eightballer/metrics:0.1.0
  host: 0.0.0.0
  port: 8889
---
public_id: eightballer/dcxt:0.1.0
type: connection
config:
  target_skill_id: eightballer/chained_dex_app:0.1.0
  exchanges:
  - name: balancer
    key_path: ethereum_private_key.txt
    ledger_id: ethereum
    rpc_url: https://rpc.ankr.com/eth
    etherscan_api_key: YOUR_ETHERSCAN_API_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    ledger_id: optimism
    rpc_url: https://mainnet.optimism.io
    etherscan_api_key: YOUR_ETHERSCAN_API_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    ledger_id: base
    rpc_url: https://base.llamarpc.com
    etherscan_api_key: YOUR_ETHERSCAN_API_KEY
