agent_name: chained_dex_app
author: eightballer
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.35.0, <3.0.0'
fingerprint:
  tests/__init__.py: bafybeibraxfmr5puv7g26bkckx3bxesc2wcjuwmd4gs4qirmgdvtbqa7ua
  tests/test_agent.py: bafybeihwx6iifsqdd5mzggpmm2gjtucwcdgnnek6oktvucoc23xa4z2urm
fingerprint_ignore_patterns: []
connections:
- eightballer/ccxt_wrapper:0.1.0:bafybeidth26t3wye3pk6gud23ngpg47z5yybp44nuxznf5zc4i2addvcgi
- eightballer/dcxt:0.1.0:bafybeiatkbuvqeqevh4dr3hlcj242vuv4uzip37w2qg2k332g4f5qntjfq
- eightballer/http_client:0.1.0:bafybeic3cvg5pyze5w2mdcnukosep7egyglnidcycliyatdnddtvufgvta
- eightballer/http_server:0.1.0:bafybeieoixhtwm6f6ednwjli3sutbgklsqhnjkgxyxeflepa4qagx5gfr4
- eightballer/prometheus:0.1.1:bafybeig7p3tzs7x4awcxjr7ctxljr6h7mrc2c36thnab6zoteualgivj6e
- valory/abci:0.1.0:bafybeib5ggind6xiilp4uclqhh27zj6ga4dfy7mdd5nxtzyr55mf3uztlu
- valory/http_client:0.23.0:bafybeiglmlwp73njl6ijmruak5ivpfx7hv6gamap72ygsvd7jmonrdtbkm
- valory/ipfs:0.1.0:bafybeifepnczgwd4pa5y535kfjphj44mbbkm7ljb6iatmxmlcu3e5mauv4
- valory/ledger:0.19.0:bafybeicib5velkx7ttqqxrbeguklyu5xeifanzqdecwalqpu3olmrjm5dq
- valory/p2p_libp2p_client:0.1.0:bafybeice5kcmpjnk65bvl4d2g2yvysiko7bgsldxtoimbl62ozgxqnjwky
contracts:
- eightballer/erc_20:0.1.0:bafybeiewlvc62xn6flmzn2dodqw3w6p3w5jqwkx36w5caznf6zjph7t2se
- valory/service_registry:0.1.0:bafybeidm5ki2bnk52janpeabjc6lsmn6w2l5zocfpnbigyfozuriv4atvy
protocols:
- eightballer/balances:0.1.0:bafybeieunsu3sfhqsh5selbbrhijedgrngjfsrzqhoevxwpv6shmlh6gni
- eightballer/default:0.1.0:bafybeidxdrzt2lqcig5cfdaju4kx2jjlbmmrvep34blhhgvm6cyr6qtlge
- eightballer/http:0.1.0:bafybeigvajfairsqyira3idfhacj7l4vq25mjgyti76et5ryhspbk5uvbi
- eightballer/markets:0.1.0:bafybeih2anyaxbqibhlufqvqx5trixarl4kmfhtatnortdrck3grjjgaga
- eightballer/ohlcv:0.1.0:bafybeicmclhj5db6fs2kf22hdgijw5hdigrii2ub4vcxcxuh7n4zxryp34
- eightballer/order_book:0.1.0:bafybeibdkpj3qy7gcybni7goneqe75cgeqcialsv6he3ozmzgqqms7oxfu
- zarathustra/asset_bridging:0.1.0:bafybeiaisse2jqpfvb2jqhgnwsa3p2b6v7ommontm5llagtfphqgkmyzkq
- eightballer/orders:0.1.0:bafybeifsi7b6pw5eifxelco7ibxjcegmhxqcyl2t2ckclmwyjdyn7wef5e
- eightballer/positions:0.1.0:bafybeicqzks7yh2zkwder2wrmt525wovl3yey2q3gcrjmi3xtthanaqhqa
- eightballer/prometheus:1.0.0:bafybeiedkmjjqbxyid67hwhpkvyknst5rdtn5pazs6rtaa3mj6r2buwl7q
- eightballer/spot_asset:0.1.0:bafybeifjra7gn24377acdpxa2p4h4u4kbfmkxw26qh5s3k2vpkb7h54d6e
- eightballer/tickers:0.1.0:bafybeigx2wpxkygmcc5c4stn44wbmjgxfojkutghaptcr2cjh5z4ojlwf4
- open_aea/signing:1.0.0:bafybeign4u6o3jtz2kuelpuhrmzosbyix2iwf7ifxythigrcuef4ybmuna
- valory/abci:0.1.0:bafybeifoxrhaouglnxqedcwybz7gt7tsnqwviqy2sl4fuzwxgwxppe46my
- valory/acn:1.1.0:bafybeihjy675e5epm3jpdmo5owtkq4xyoxaif2rnyanrbvly63we37fdbm
- valory/contract_api:1.0.0:bafybeidpch6cvuweq5x4h6ummnnw5xynmfsbj3sxm2m63seuqizrmvpd3e
- valory/http:1.0.0:bafybeic2kgzaesbi6tio5wohr6sj6lq7zaxa3mxhwza52qmdlm6ai3lmrm
- valory/ipfs:0.1.0:bafybeid56ir7oghnxugb2wyszjcj6l5siznimjdm5av3f24kp44ci7kg2q
- valory/ledger_api:1.0.0:bafybeic5qfhodpwqjdkwxs4gzummpc3dxbpn4egg7s7f2gibfopa4nxz4i
- valory/tendermint:0.1.0:bafybeicpmyfpmoobve6eqjbrs4ht5apl5xvnikmsg4wdcpwljy42zhghl4
skills:
- eightballer/abstract_round_abci:0.1.0:bafybeifazgkeuphhaiml5v26weiio6qpaa2ax57hnnbwijs5gpxs6gxhna
- eightballer/metrics:0.1.0:bafybeifa4yxuoskhgjdl7xhodksgzlm62ucqbdqu4yb7ppjma6fdv2tzeq
- eightballer/prometheus:0.1.0:bafybeifnee635625vabb45qotvzopgkets5dlwk3mwae3lrhr4bqfpuxyy
- eightballer/registration_abci:0.1.0:bafybeic3y42yhx7jrktb3yx3xgs56t55r335anrxaq6y54szzswyz2iua4
- eightballer/reset_pause_abci:0.1.0:bafybeif54yskkjrdxv2eemk6ed2xrlng3vwpf4rftot5cbubivvqymmepi
- valory/abstract_abci:0.1.0:bafybeieactg2rjpeomiqzuu3nbanoxtfdfk5vwil2dqg5ceh6z7kxl7snq
- eightballer/chained_dex_app:0.1.0:bafybeic4bppqrmvaxhpniodu6kezjtjirht4nwhvrkqjt445lgquzfyt2q
- eightballer/dex_data_retrieval:0.1.0:bafybeidy77vbun7wv5ncqjdyg2ozmeleapfa7vckts6nmfitdc65vqh2hu
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: true
  version: 1
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      level: INFO
      stream: ext://sys.stdout
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: INFO
  loggers:
    aea:
      handlers:
      - console
      - logfile
      level: INFO
      propagate: false
dependencies:
  open-aea-ledger-ethereum: {}
customs: []
default_connection: null
---
public_id: valory/ipfs:0.1.0:bafybeiatjutuiav7oxl4hszy3oypdwuetr6crjpminush54c5k4nbeciv4
type: connection
config:
  ipfs_domain: /dns/registry.autonolas.tech/tcp/443/https
---
public_id: valory/abci:0.1.0:bafybeihofnsokowicviac6yz3uhur52l3mf54s2hz4i2je5ie4vlruouga
type: connection
config:
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
  target_skill_id: eightballer/chained_dex_app:0.1.0
---
public_id: eightballer/prometheus:0.1.1:bafybeiemx6sryvqdjied7xqqxge5vyplyyzyiro4a4pubqpjrps4sxm7xe
type: connection
config:
  port: 8888
  host: 0.0.0.0
---
public_id: eightballer/http_server:0.1.0:bafybeih7adv4sxwek3g3ns6x6sguhnos7ixmsdaywqdaxhexczm2gotivm
type: connection
config:
  target_skill_id: eightballer/metrics:0.1.0
  host: 0.0.0.0
  port: 8889
---
public_id: eightballer/dcxt:0.1.0
type: connection
config:
  target_skill_id: eightballer/chained_dex_app:0.1.0
  exchanges:
  - name: balancer
    key_path: ethereum_private_key.txt
    ledger_id: ethereum
    rpc_url: https://rpc.ankr.com/eth
    etherscan_api_key: YOUR_ETHERSCAN_API_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    ledger_id: optimism
    rpc_url: https://mainnet.optimism.io
    etherscan_api_key: YOUR_ETHERSCAN_API_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    ledger_id: base
    rpc_url: https://base.drpc.org
    etherscan_api_key: YOUR_ETHERSCAN_API_KEY
---
public_id: eightballer/chained_dex_app:0.1.0
type: skill
models:
  params:
    args:
      dex_data_retrieval_config:
        enabled: true
        reporting_enabled: true
        exchange_ids:
        - balancer_optimism
        - balancer_ethereum
        - balancer_base
        extra_kwargs: {}
        backoff: 1.0
        retries: 3
      max_healthcheck: 1200
      on_chain_service_id: null
      reset_pause_duration: 10
      reset_tendermint_after: 10
      round_timeout_seconds: 35.0
      service_registry_address: null
      setup:
        all_participants: ${list:["0x92d9610BC04aa4F0162e45B031b7fa6d76d4B4b3"]}
        consensus_threshold: 1
        safe_contract_address: '0x0000000000000000000000000000000000000000'
      share_tm_config_on_startup: false
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_p2p_url: ${str:localhost:26656}
      tendermint_url: ${str:http://localhost:26657}
      validate_timeout: 1205
