agent_name: chained_dex_app
author: eightballer
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.35.0, <2.0.0'
fingerprint:
  tests/__init__.py: bafybeibraxfmr5puv7g26bkckx3bxesc2wcjuwmd4gs4qirmgdvtbqa7ua
  tests/test_agent.py: bafybeicowtnq5n4ick4cqbhsgeiuvue4q5dmtdcdljeihdwptiu54vqevu
fingerprint_ignore_patterns: []
connections:
- eightballer/ccxt:0.1.0:bafybeiakskxkscwf22jvkfwyxwsxxyt2gnkbs7mefqcjzak3k7v3q4pmxm
- eightballer/dcxt:0.1.0:bafybeidi5eb4xedqsazjksefhujmik2keennh4oxyyrq73t63ya5ffcuv4
- eightballer/http_client:0.1.0:bafybeihli73baanti52hpp3gnsgvfsx5rkpfprnzazmi3pamwafvngvnu4
- eightballer/http_server:0.1.0:bafybeicsx5ayj37c27a4ffsd4f6ydr5lsed53rn3tkdzxar22da5raaoqm
- eightballer/prometheus:0.1.1:bafybeic452zt5tex4uxlrpax33spgj3dor26rulesszyex2orjz5dhllkq
- valory/abci:0.1.0:bafybeifu42n4vz3bid3nkbr7sea6d3pfmxx7rzctr37ovafmbpyq6vplkm
- valory/http_client:0.23.0:bafybeid5ffvg76ejjoese7brj5ji3lx66cu7p2ixfwflpo6rgofkypfd7y
- valory/ipfs:0.1.0:bafybeigjspoceazd5roxo4pcqcgyu3ozixkdoc44domwcaumt2zwoz2x3m
- valory/ledger:0.19.0:bafybeibiayfscw4badpr545f47hsvc2r5lgfpgzib5q4h4u6kkosdsytby
- valory/p2p_libp2p_client:0.1.0:bafybeic6ayusdwy4dks75njwk32ac7ur7salgllwf4fdc34ue5z2k5iz4q
contracts:
- valory/service_registry:0.1.0:bafybeibuq4p66jdpnrq7viz4zylydu3zneteukfy3gwdgp273vptnq3dvi
- eightballer/erc_20:0.1.0:bafybeic3l7dsgtui5apfqcoq2i5q2adorb7s24lf5ksgk545a7ttxswtqu
protocols:
- eightballer/balances:0.1.0:bafybeieusqlzcwbnzshadmt35hstiwdhrvbkd46oejcpwyq7tm66pb3ive
- eightballer/default:0.1.0:bafybeigicpslawpiohf2gzhziv53jlvotfiknwpvbrt7sxsusriuq4su5a
- eightballer/http:0.1.0:bafybeieexnvev3uegukhfnackqq2ooceiqcnu7q7e4w73wyohvfjod6bqq
- eightballer/markets:0.1.0:bafybeihwx4wombh5r7mtfpags466w2vcydy6ldl3c3awnwtgizpfllomse
- eightballer/ohlcv:0.1.0:bafybeicaxvy6itmm52gqofmm7yq5xgojyrge6uczgwcsxeykxjju5xk66a
- eightballer/order_book:0.1.0:bafybeig4e26oyh5qpcx26glqm3zvxzu5cks5guf7ejtw6edkse63epr6ky
- eightballer/orders:0.1.0:bafybeihx74ubnyd2uyjc53wq4732b5v4umdbv4poofkjtsl5fsaj5rdyom
- eightballer/positions:0.1.0:bafybeiaf2zettrz53zgegzzawukd7j4cvbi4jbpkppmfgk6dvyoz5e72ry
- eightballer/prometheus:1.0.0:bafybeibvuazvki5pbeakpvcjm7icgf4wosacpcfnpyr4tk5dz3egoqny4a
- eightballer/spot_asset:0.1.0:bafybeic4swpkiw3p6kmz5l53siitz6dk62fidqqdeak26g5bei7vkhrwwi
- eightballer/tickers:0.1.0:bafybeic4ltzxy3wl2a43bwsoyohtcf5cuypdbtsgdrlhxwnaxklf564zgm
- open_aea/signing:1.0.0:bafybeig2d36zxy65vd7fwhs7scotuktydcarm74aprmrb5nioiymr3yixm
- valory/abci:0.1.0:bafybeiatodhboj6a3p35x4f4b342lzk6ckxpud23awnqbxwjeon3k5y36u
- valory/acn:1.1.0:bafybeic6h55ov5lrzbah6fate54c4u6spopcexxspw3abotbmffabfddeu
- valory/contract_api:1.0.0:bafybeid247uig2ekykdumh7ewhp2cdq7rchaeqjj6e7urx35zfpdl5zrn4
- valory/http:1.0.0:bafybeih4azmfwtamdbkhztkm4xitep3gx6tfdnoz6tvllmaqnhu3klejfa
- valory/ipfs:0.1.0:bafybeifi2nri7sprmkez4rqzwb4lnu6peoy3bax5k6asf6k5ms7kmjpmkq
- valory/ledger_api:1.0.0:bafybeihmqzcbj6t7vxz2aehd5726ofnzsfjs5cwlf42ro4tn6i34cbfrc4
- valory/tendermint:0.1.0:bafybeigydrbfrlmr4f7shbtqx44kvmbg22im27mxdap2e3m5tkti6t445y
skills:
- eightballer/chained_dex_app:0.1.0:bafybeidrqlveffocymsrytqt3bmsruc4mcieksz3of7wnlszr7vf6us6ou
- eightballer/dex_data_retrieval:0.1.0:bafybeig4bl4xctzrhbs57pxk26y4nsllt2dgzdapswriob7kcxm6hhhyma
- eightballer/metrics:0.1.0:bafybeib75valh7sd5za6msuahonys6nvn322rnkjcd6kjg6odnkpfgj5bi
- eightballer/prometheus:0.1.0:bafybeibhcoshmv7dz64rnhfablamxb6gpg6w4nyeuw44ilscjswt26dhhe
- valory/abstract_abci:0.1.0:bafybeifv2dynqo3o57nr6jntsvdkduytz3f6i52csv2bjwrr4qhi4mkm7i
- valory/abstract_round_abci:0.1.0:bafybeiba3zhx5drsf7ailfboeuvwykocmkffs2j426u4q7d4erig67lyhm
- valory/registration_abci:0.1.0:bafybeigp2g6uhhgjlkqyhjlk4abfjuecmulnwlki6acbpfu45thslqujlu
- valory/reset_pause_abci:0.1.0:bafybeidhqvc4cl6alvkql5kadiv7snudl7o2ctfqbmhrihtejm3zhkmbby
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: true
  version: 1
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      level: INFO
      stream: ext://sys.stdout
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: INFO
  loggers:
    aea:
      handlers:
      - console
      - logfile
      level: INFO
      propagate: false
dependencies:
  open-aea-ledger-ethereum: {}
customs: []
default_connection: null
---
public_id: valory/ipfs:0.1.0:bafybeiatjutuiav7oxl4hszy3oypdwuetr6crjpminush54c5k4nbeciv4
type: connection
config:
  ipfs_domain: /dns/registry.autonolas.tech/tcp/443/https
---
public_id: valory/abci:0.1.0:bafybeihofnsokowicviac6yz3uhur52l3mf54s2hz4i2je5ie4vlruouga
type: connection
config:
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
  target_skill_id: eightballer/chained_dex_app:0.1.0
---
public_id: eightballer/chained_dex_app:0.1.0:bafybeicmuthcay6doky6sgy235n52chsk5fkzswpvyg5s4yeptvmzmxoqy
type: skill
models:
  params:
    args:
      dex_data_retrieval_config:
        enabled: true
        reporting_enabled: true
        exchange_ids:
        - balancer_optimism
        - balancer_ethereum
        - balancer_base
        extra_kwargs: {}
        backoff: 1.0
        retries: 3
      max_healthcheck: 1200
      on_chain_service_id: null
      reset_pause_duration: 10
      reset_tendermint_after: 10
      round_timeout_seconds: 35.0
      service_registry_address: null
      setup:
        all_participants: ${list:["0x92d9610BC04aa4F0162e45B031b7fa6d76d4B4b3"]}
        consensus_threshold: 1
        safe_contract_address: '0x0000000000000000000000000000000000000000'
      share_tm_config_on_startup: false
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_p2p_url: ${str:localhost:26656}
      tendermint_url: ${str:http://localhost:26657}
      validate_timeout: 1205
---
public_id: eightballer/prometheus:0.1.1:bafybeiemx6sryvqdjied7xqqxge5vyplyyzyiro4a4pubqpjrps4sxm7xe
type: connection
config:
  port: 8888
  host: 0.0.0.0
---
public_id: eightballer/http_server:0.1.0:bafybeih7adv4sxwek3g3ns6x6sguhnos7ixmsdaywqdaxhexczm2gotivm
type: connection
config:
  target_skill_id: eightballer/metrics:0.1.0
  host: 0.0.0.0
  port: 8889
---
public_id: eightballer/dcxt:0.1.0
type: connection
config:
  target_skill_id: eightballer/chained_dex_app:0.1.0
  exchanges:
  - name: balancer
    key_path: ethereum_private_key.txt
    ledger_id: ethereum
    rpc_url: https://rpc.ankr.com/eth
    etherscan_api_key: YOUR_ETHERSCAN_API_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    ledger_id: optimism
    rpc_url: https://mainnet.optimism.io
    etherscan_api_key: YOUR_ETHERSCAN_API_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    ledger_id: base
    rpc_url: https://base.llamarpc.com
    etherscan_api_key: YOUR_ETHERSCAN_API_KEY
