name: sol_evm_arbitrage
author: eightballer
version: 0.1.0
description: An agent service to demonstrate simple usage of DCXT and CCXT libraries
  to perform arbitrage between solana and ethereum.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: eightballer/trader:0.1.0:bafybeifkaa7dhzihnmyxjdfxggiqyigoy4pemwjuxmgofofegv3yjcw4ti
number_of_agents: 1
deployment:
  agent:
    ports:
      0:
        8000: 8890
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
0:
  config:
    host: 0.0.0.0
    port: 8888
    target_skill_id: eightballer/metrics:0.1.0
---
public_id: eightballer/ccxt:0.1.0:bafybeidyrx74rtv7x3h757y44cc5xle6crnnklwpe6jrgwmsfjdtk5xabe
type: connection
config:
  exchanges: []
  target_skill_id: eightballer/simple_fsm:0.1.0
---
public_id: eightballer/apprise:0.1.0
type: connection
config:
  endpoints:
  - ${APPRISE_ENDPOINT:str}
