agent_name: trader
author: eightballer
version: 0.1.0
license: Apache-2.0
description: Simple Agent to demonstrate Dex-Cex Arbitrage
aea_version: '>=1.55.0, <3.0.0'
fingerprint:
  tests/test_trader_agent.py: bafybeibcg6glyfbifp7sagmxvwbqiomc276su526xdzrwjkxfdqunvjzna
fingerprint_ignore_patterns: []
connections:
- eightballer/apprise_wrapper:0.1.0:bafybeib46mwxydjapluicictavkcsmt2jpppkkru4lqhv3fwx5pbmngi2u
- eightballer/ccxt_wrapper:0.1.0:bafybeidth26t3wye3pk6gud23ngpg47z5yybp44nuxznf5zc4i2addvcgi
- eightballer/dcxt:0.1.0:bafybeiciybmksirpc7evytvokxhs7pkveepoyk3zqu5ubroh33dca6i2hy
- eightballer/http_client:0.1.0:bafybeic3cvg5pyze5w2mdcnukosep7egyglnidcycliyatdnddtvufgvta
- eightballer/http_server:0.1.0:bafybeieoixhtwm6f6ednwjli3sutbgklsqhnjkgxyxeflepa4qagx5gfr4
- eightballer/prometheus:0.1.1:bafybeig7p3tzs7x4awcxjr7ctxljr6h7mrc2c36thnab6zoteualgivj6e
- valory/abci:0.1.0:bafybeib5ggind6xiilp4uclqhh27zj6ga4dfy7mdd5nxtzyr55mf3uztlu
- valory/http_client:0.23.0:bafybeiazlocje3lt6cqw3avcl4cfjijlhnbzcq22g3yvo3jtvoh4ecds3y
- valory/ipfs:0.1.0:bafybeifepnczgwd4pa5y535kfjphj44mbbkm7ljb6iatmxmlcu3e5mauv4
- valory/ledger:0.19.0:bafybeifjtwsl47skzlo3s6kfevy5dplzmb7ptcnehasszwmuta7lyqq5ci
- valory/p2p_libp2p_client:0.1.0:bafybeiho7skqns3kgb4oqo4pec44y5unwfzh6kz5fei35wls5ndobmufu4
contracts:
- eightballer/erc_20:0.1.0:bafybeiewlvc62xn6flmzn2dodqw3w6p3w5jqwkx36w5caznf6zjph7t2se
- eightballer/spl_token:0.1.0:bafybeieozewfydqtdlygehzkhofque6klpcr6pkkcx5bd3eug7uuwcl7nm
- vybe/jupitar_swap:0.1.0:bafybeiaaw2eblwy4z43xizkyhy4noc2q4hydu7vw7ejr7npkifhg6yx6yq
- valory/service_registry:0.1.0:bafybeidm5ki2bnk52janpeabjc6lsmn6w2l5zocfpnbigyfozuriv4atvy
protocols:
- eightballer/balances:0.1.0:bafybeieunsu3sfhqsh5selbbrhijedgrngjfsrzqhoevxwpv6shmlh6gni
- eightballer/default:0.1.0:bafybeidxdrzt2lqcig5cfdaju4kx2jjlbmmrvep34blhhgvm6cyr6qtlge
- eightballer/http:0.1.0:bafybeigvajfairsqyira3idfhacj7l4vq25mjgyti76et5ryhspbk5uvbi
- eightballer/markets:0.1.0:bafybeih2anyaxbqibhlufqvqx5trixarl4kmfhtatnortdrck3grjjgaga
- eightballer/ohlcv:0.1.0:bafybeicmclhj5db6fs2kf22hdgijw5hdigrii2ub4vcxcxuh7n4zxryp34
- eightballer/order_book:0.1.0:bafybeibdkpj3qy7gcybni7goneqe75cgeqcialsv6he3ozmzgqqms7oxfu
- eightballer/orders:0.1.0:bafybeifsi7b6pw5eifxelco7ibxjcegmhxqcyl2t2ckclmwyjdyn7wef5e
- eightballer/positions:0.1.0:bafybeicqzks7yh2zkwder2wrmt525wovl3yey2q3gcrjmi3xtthanaqhqa
- eightballer/prometheus:1.0.0:bafybeiedkmjjqbxyid67hwhpkvyknst5rdtn5pazs6rtaa3mj6r2buwl7q
- eightballer/spot_asset:0.1.0:bafybeifjra7gn24377acdpxa2p4h4u4kbfmkxw26qh5s3k2vpkb7h54d6e
- eightballer/tickers:0.1.0:bafybeigx2wpxkygmcc5c4stn44wbmjgxfojkutghaptcr2cjh5z4ojlwf4
- eightballer/user_interaction:0.1.0:bafybeibotsfodi6jkoemmt4tpwecxkj7p3dphinuzuakh5z2cisckxxp6m
- open_aea/signing:1.0.0:bafybeign4u6o3jtz2kuelpuhrmzosbyix2iwf7ifxythigrcuef4ybmuna
- valory/abci:0.1.0:bafybeifoxrhaouglnxqedcwybz7gt7tsnqwviqy2sl4fuzwxgwxppe46my
- valory/acn:1.1.0:bafybeid7fbmi52oz2g2saotokgpfrb37eq66acjj5uclt3qcad6pvqeuom
- valory/contract_api:1.0.0:bafybeiegdpxw24ozrfu3ocmio7fsv2phhfcxgbe546t5ux5ejfscwnpdyq
- valory/http:1.0.0:bafybeicpqv6by2ry6gie62awiwocot77sx46fv3g3vmjwkci4rl3n4xyby
- valory/ipfs:0.1.0:bafybeid56ir7oghnxugb2wyszjcj6l5siznimjdm5av3f24kp44ci7kg2q
- valory/ledger_api:1.0.0:bafybeie45kvlznnafdcnqicxfczfeqfpgxo7wskboheoexadjgml3pkahq
- valory/tendermint:0.1.0:bafybeicpmyfpmoobve6eqjbrs4ht5apl5xvnikmsg4wdcpwljy42zhghl4
skills:
- eightballer/metrics:0.1.0:bafybeifa4yxuoskhgjdl7xhodksgzlm62ucqbdqu4yb7ppjma6fdv2tzeq
- eightballer/prometheus:0.1.0:bafybeifnee635625vabb45qotvzopgkets5dlwk3mwae3lrhr4bqfpuxyy
- eightballer/simple_fsm:0.1.0:bafybeibkurnlpwtnkbxebfopa6a32vpvwc2fhdixlv27fn67x744nyet2m
- valory/abstract_abci:0.1.0:bafybeieactg2rjpeomiqzuu3nbanoxtfdfk5vwil2dqg5ceh6z7kxl7snq
- eightballer/abstract_round_abci:0.1.0:bafybeiavy2pdm2kweyecbexz5eipai5mpceos7fjgyhcn6z6wqu6ok673m
customs:
- eightballer/arbitrage_strategy:0.1.0:bafybeiaacwheojls4fbzjm3teyrahsaq4aznjejdmpjpvobr4t6vdrqoli
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: true
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  handlers:
    console:
      class: rich.logging.RichHandler
      level: INFO
    logfile:
      class: logging.FileHandler
      filename: log.txt
      formatter: standard
      level: INFO
  loggers:
    aea:
      handlers:
      - console
      - logfile
      level: INFO
      propagate: false
  version: 1
dependencies:
  open-aea-ledger-ethereum:
    version: ==2.0.6
  open-aea-test-autonomy:
    version: ==0.21.5
default_connection: null
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: eightballer/metrics:0.1.0
---
public_id: eightballer/prometheus:0.1.1:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8716
---
public_id: valory/abci:0.1.0:bafybeihofnsokowicviac6yz3uhur52l3mf54s2hz4i2je5ie4vlruouga
type: connection
config:
  host: ${str:localhost}
  port: 26658
  use_tendermint: ${bool:false}
  target_skill_id: eightballer/chained_dex_app:0.1.0
---
public_id: eightballer/ccxt_wrapper:0.1.0:bafybeidyrx74rtv7x3h757y44cc5xle6crnnklwpe6jrgwmsfjdtk5xabe
type: connection
config:
  exchanges:
  - name: mexc
    api_key: ${str:YOUR_KEY}
    api_secret: ${str:YOUR_SECRET}
  - name: poloniex
    api_key: ${str:YOUR_KEY}
    api_secret: ${str:YOUR_SECRET}
  target_skill_id: eightballer/simple_fsm:0.1.0
---
public_id: eightballer/apprise_wrapper:0.1.0
type: connection
config:
  endpoints:
  - ${str:ntfy://ntfy.sh/agent-arbing}
---
public_id: eightballer/dcxt:0.1.0:bafybeid2knx2lkd5jz64a357vtcz35gfjtoqey4shmmjtygl3r7dx6kvwq
type: connection
config:
  exchanges:
  - name: balancer
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: base
    rpc_url: https://mainnet.base.org
    etherscan_api_key: YOUR_ETHERSCAN_API_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: mode
    rpc_url: https://mode.drpc.org
    etherscan_api_key: YOUR_ETHERSCAN_API_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: gnosis
    rpc_url: http://gnosis.chains.wtf:8545
    etherscan_api_key: YOUR_ETHERSCAN_API_KEY
---
public_id: eightballer/simple_fsm:0.1.0:bafybeigkm75xwd7jw2onypx27bzokkcwwrvwlm4nd6zr7e6ujrn3tw76fa
type: skill
models:
  arbitrage_strategy:
    args:
      dexs:
        cowswap:
        - base
        - gnosis
        balancer: []
      strategy_public_id: eightballer/lbtc_arbitrage:0.1.0
      strategy_init_kwargs:
        base_asset: ${BASE_ASSET:str:USDC}
        quote_asset: ${QUOTE_ASSET:str:OLAS}
        order_size: ${ORDER_SIZE:float:0.1}
        min_profit: ${MIN_PROFIT:float:0.01}
      cexs: ${list:[]}
