agent_name: trader
author: eightballer
version: 0.1.0
license: Apache-2.0
description: Simple Agent to demonstrate Dex-Cex Arbitrage
aea_version: '>=1.55.0, <3.0.0'
fingerprint:
  tests/test_trader_agent.py: bafybeibcg6glyfbifp7sagmxvwbqiomc276su526xdzrwjkxfdqunvjzna
fingerprint_ignore_patterns: []
connections:
- eightballer/apprise_wrapper:0.1.0:bafybeiafvyh2l3imqusjn374wnnet6gzhyvc4o5wrczdlt3mz535og7elm
- eightballer/ccxt_wrapper:0.1.0:bafybeidth26t3wye3pk6gud23ngpg47z5yybp44nuxznf5zc4i2addvcgi
- eightballer/dcxt:0.1.0:bafybeif4j7ehfhd57jhdtlwy6tfobkh5r5ye5hszlfn6em5gnudilsz3lu
- eightballer/http_client:0.1.0:bafybeigqr2eudiwksmr2cavk6as63li2oqf3x2edwzvs5vepntuqhemnge
- eightballer/http_server:0.1.0:bafybeieispawqnpoeqidgkt7u7vsynualtcmbs3vsgggpb6hzkdsyd3fve
- eightballer/prometheus:0.1.1:bafybeicgvmn5eo57jotbcwasjqlmzog3ss5dvvembw7jaytfz33z4kbaoa
- valory/abci:0.1.0:bafybeibtiw6wlcrkov6vshboixsjgaeodkhxjppk2fbzwleknbp24ci42i
- valory/http_client:0.23.0:bafybeifcxgtlp3rcuptxtu7fkipauuxl3mcbawuofe6nnejhnq3mjw2rjq
- valory/ipfs:0.1.0:bafybeif7exoq2viwhfgfcjplxq73hnxvgpsx7pwshhntx6aekza25mdwli
- valory/ledger:0.19.0:bafybeiflmep26twrfk25olhyxuagceaa2cfvg5qtgsisaxh6z4pdapg6dy
- valory/p2p_libp2p_client:0.1.0:bafybeibk6bbwkwfar6ck4vkr5bgsbyigavgmxgdoimqw4d4gqo2t2ajixa
contracts:
- eightballer/erc_20:0.1.0:bafybeiewlvc62xn6flmzn2dodqw3w6p3w5jqwkx36w5caznf6zjph7t2se
- eightballer/spl_token:0.1.0:bafybeieozewfydqtdlygehzkhofque6klpcr6pkkcx5bd3eug7uuwcl7nm
- vybe/jupitar_swap:0.1.0:bafybeiaaw2eblwy4z43xizkyhy4noc2q4hydu7vw7ejr7npkifhg6yx6yq
- valory/service_registry:0.1.0:bafybeigcr4y6ylathz5owdyq6nhvrdpv5unyeb3ol3h3xbncq24useqlpa
protocols:
- eightballer/balances:0.1.0:bafybeieunsu3sfhqsh5selbbrhijedgrngjfsrzqhoevxwpv6shmlh6gni
- eightballer/default:0.1.0:bafybeidxdrzt2lqcig5cfdaju4kx2jjlbmmrvep34blhhgvm6cyr6qtlge
- eightballer/http:0.1.0:bafybeigvajfairsqyira3idfhacj7l4vq25mjgyti76et5ryhspbk5uvbi
- eightballer/markets:0.1.0:bafybeih2anyaxbqibhlufqvqx5trixarl4kmfhtatnortdrck3grjjgaga
- eightballer/ohlcv:0.1.0:bafybeicmclhj5db6fs2kf22hdgijw5hdigrii2ub4vcxcxuh7n4zxryp34
- eightballer/order_book:0.1.0:bafybeibdkpj3qy7gcybni7goneqe75cgeqcialsv6he3ozmzgqqms7oxfu
- eightballer/orders:0.1.0:bafybeifsi7b6pw5eifxelco7ibxjcegmhxqcyl2t2ckclmwyjdyn7wef5e
- eightballer/positions:0.1.0:bafybeicqzks7yh2zkwder2wrmt525wovl3yey2q3gcrjmi3xtthanaqhqa
- eightballer/prometheus:1.0.0:bafybeiedkmjjqbxyid67hwhpkvyknst5rdtn5pazs6rtaa3mj6r2buwl7q
- eightballer/spot_asset:0.1.0:bafybeifjra7gn24377acdpxa2p4h4u4kbfmkxw26qh5s3k2vpkb7h54d6e
- eightballer/tickers:0.1.0:bafybeigx2wpxkygmcc5c4stn44wbmjgxfojkutghaptcr2cjh5z4ojlwf4
- eightballer/user_interaction:0.1.0:bafybeidhs7hwsfinvgkkyodgq5qoolg5i4rf5vr2c2xcuvkbyoodefcvoq
- open_aea/signing:1.0.0:bafybeigalbjxbpl6pezijj6it2zspjcjy3znm66t5ygbe4kz5kxcnbu65y
- valory/abci:0.1.0:bafybeigdi6wsbdn2nv7clzhnuhki3taywgiiajwawdaat57o5ntlgqj2qe
- valory/acn:1.1.0:bafybeihrfsualuoxnwxfmhgbbyty4ttqijuwzcesg3kwsqxfzcmxc7t4rm
- valory/contract_api:1.0.0:bafybeigzv2yxgkednegkiepkm5uxv2ekdn3y5czvh6ycba6t7n3k2otu24
- valory/http:1.0.0:bafybeiczj4q3lkuiwhb6vzn7ptxifqgjtnvl7722t7c4eystbuel5cd34i
- valory/ipfs:0.1.0:bafybeib7jhgyocjwdq3r5wzq3z4qeubj3dwi3aqjn2uxzuwnjp5fhvafcu
- valory/ledger_api:1.0.0:bafybeicwup3faznzvuciqkljejo2c6gbv3dliaglscf5bibu6633tylkfq
- valory/tendermint:0.1.0:bafybeif5wq5i2ugr66alniej2bk4vws5sikal7otx674y5kz52e3ulo2qm
skills:
- eightballer/metrics:0.1.0:bafybeifa4yxuoskhgjdl7xhodksgzlm62ucqbdqu4yb7ppjma6fdv2tzeq
- eightballer/prometheus:0.1.0:bafybeidfz7ms5n7f27fywsm4gbxy6ykztdctln44cvuemmyuww2igonwby
- eightballer/simple_fsm:0.1.0:bafybeihqbapyh57blyqmkrhlgalas67w2rdqqqwh4m25opr4o5hafxk5va
- valory/abstract_abci:0.1.0:bafybeidr3dqykchbw7rnmxcrp3qkuafk24pyvr7zehfbkcfon62qwuft7y
- eightballer/abstract_round_abci:0.1.0:bafybeibaxi47gozccfsf7j2bizthfw7t6zs5ajfynq5eju42bnvb5glc7i
customs:
- eightballer/arbitrage_strategy:0.1.0:bafybeiaacwheojls4fbzjm3teyrahsaq4aznjejdmpjpvobr4t6vdrqoli
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: true
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  handlers:
    console:
      class: rich.logging.RichHandler
      level: INFO
    logfile:
      class: logging.FileHandler
      filename: log.txt
      formatter: standard
      level: INFO
  loggers:
    aea:
      handlers:
      - console
      - logfile
      level: INFO
      propagate: false
  version: 1
dependencies:
  open-aea-ledger-ethereum:
    version: ==2.0.6
  open-aea-test-autonomy:
    version: ==0.21.5
default_connection: null
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: eightballer/metrics:0.1.0
---
public_id: eightballer/prometheus:0.1.1:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8716
---
public_id: valory/abci:0.1.0:bafybeihofnsokowicviac6yz3uhur52l3mf54s2hz4i2je5ie4vlruouga
type: connection
config:
  host: ${str:localhost}
  port: 26658
  use_tendermint: ${bool:false}
  target_skill_id: eightballer/chained_dex_app:0.1.0
---
public_id: eightballer/ccxt_wrapper:0.1.0:bafybeidyrx74rtv7x3h757y44cc5xle6crnnklwpe6jrgwmsfjdtk5xabe
type: connection
config:
  exchanges:
  - name: mexc
    api_key: ${str:YOUR_KEY}
    api_secret: ${str:YOUR_SECRET}
  - name: poloniex
    api_key: ${str:YOUR_KEY}
    api_secret: ${str:YOUR_SECRET}
  target_skill_id: eightballer/simple_fsm:0.1.0
---
public_id: eightballer/apprise_wrapper:0.1.0
type: connection
config:
  endpoints:
  - ${str:ntfy://ntfy.sh/agent-arbing}
---
public_id: eightballer/dcxt:0.1.0:bafybeid2knx2lkd5jz64a357vtcz35gfjtoqey4shmmjtygl3r7dx6kvwq
type: connection
config:
  exchanges:
  - name: balancer
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: base
    rpc_url: https://mainnet.base.org
    etherscan_api_key: YOUR_ETHERSCAN_API_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: mode
    rpc_url: https://mode.drpc.org
    etherscan_api_key: YOUR_ETHERSCAN_API_KEY
  - name: balancer
    key_path: ethereum_private_key.txt
    wallet: null
    ledger_id: gnosis
    rpc_url: http://gnosis.chains.wtf:8545
    etherscan_api_key: YOUR_ETHERSCAN_API_KEY
---
public_id: eightballer/simple_fsm:0.1.0:bafybeigkm75xwd7jw2onypx27bzokkcwwrvwlm4nd6zr7e6ujrn3tw76fa
type: skill
models:
  arbitrage_strategy:
    args:
      dexs:
        cowswap:
        - base
        - gnosis
        balancer: []
      strategy_public_id: eightballer/lbtc_arbitrage:0.1.0
      strategy_init_kwargs:
        base_asset: ${BASE_ASSET:str:USDC}
        quote_asset: ${QUOTE_ASSET:str:OLAS}
        order_size: ${ORDER_SIZE:float:0.1}
        min_profit: ${MIN_PROFIT:float:0.01}
      cexs: ${list:[]}
